### ISSUE TITLE
Update description of issue templates

### ISSUE THREAD

**Issue by luongvo** [nimblehq/flutter_templates#104]
## Why

- `story_template.md`: We are not using this template at all, so let's remove it
- Add 2 new links in [new `Issue` section](https://github.com/nimblehq/android-templates/issues/new/choose):
  - Request For Comments (RFC)
  - Ask a question

![image](https://user-images.githubusercontent.com/16315358/193763341-cc26b383-59c2-4625-84eb-c0f7fb555c60.png)

## Who Benefits?

I think this is **essential**, as it will bring a good experience for the developers themselves

**Comment by manh-t** [comment]
+1
