### ISSUE TITLE
Add codecov to the ci/cd pipeline of the project

### ISSUE THREAD

**Issue by sleepylee** [nimblehq/flutter_templates#21]
## Why

We need to keep our test coverage under observation. This helps the team to always be aware of new code being added are tested thoroughly before getting out to be used by someone else.

If you agree to this proposal, please give a thumb up 👍 
 
## Who Benefits?

Developers

**Comment by luongvo** [comment]
Oops, I accidentally added CodeCov integration in PR #45 🤪 

@markgravity @doannimble Could you please give your ideas about this integration then I can grab this ticket also 💪

**Comment by doannimble** [comment]
@luongvo As it is a small thing, then we can grab it in this ticket 👌

**Comment by luongvo** [comment]
@manh-t Hey, we're not finishing this ticket yet 🤔 I removed the CodeCov integration out of #45 already.

**Comment by manh-t** [comment]
@luongvo oh, this issue is auto closed 💦
