### ISSUE TITLE
[RFC] Add `fluro` as a Navigator of the project

### ISSUE THREAD

**Issue by manh-t** [nimblehq/flutter_templates#23]
## Why

We should create a `navigator` wrapper and let the app inject it instead of using the built-in `Navigator`. The necessary lib: [Fluro](https://pub.dev/packages/fluro)

Pros:
- Can define `GlobalKey<NavigatorState>` inside, so no need to pass `BuildContext` to the Navigator.
- Wildcard parameter matching
- Can custom the transition easily
- Can support implementing the deeplink later.
- Easy mock.

Cons: Not found yet.

You can find the example [here](https://github.com/nimblehq/flutter_dm_module/pull/15/files).

If you agree to this proposal, please give a thumb up 👍
 
## Who Benefits?

Developers

**Comment by sleepylee** [comment]
not sure about this imma have to spend some time reading & trying before giving the vote 👀  it's new to me.

**Comment by manh-t** [comment]
@sleepylee I found this lib when researching the Flutter techniques. Technically, we don't need to reinvent the wheel by writing the util functions like `clear the stack`, `perform specific transition` etc, and many more nice features. Tbh, I haven't explored it all but sounds promising. You may give it a try 😄

**Comment by sleepylee** [comment]
@manh-t 😂  I used this: https://github.com/jonataslaw/getx/blob/master/documentation/en_US/route_management.md. It was the same idea with the navigation + clean stack back (offAll()) and possible to add custom `transition` animation too 😂  would you like to consider it?

**Comment by manh-t** [comment]
But should we add a `Get` package to use only one `navigator` function? 😂 Seems we have to apply the `Get` ecosystem in order to use its util functions 🤪 
Honestly, `Get`'s author added many useful extension functions and I would like to have it :harold:

**Comment by sleepylee** [comment]
should we then? 🐤  remember that we don't necessarily use everything from them; i.e if you prefer using a different package for DI / State Management / Navigation that's totally fine 😛  if we go with `GetX` we shall reduce many other parts too. The concern mainly to me is: do we need to put them on implemented? Can they be plugged in when init the project i.e: using `GetX` or `Fluro` as the choice of navigation 🤷

**Comment by doannimble** [comment]
IMO, I would like to use `GetX`, even for `State Management` 😄

**Comment by sleepylee** [comment]
@doannimble I found that GetX has a few weird issues when I was completing my IC with GetX (for everything). The most significant issue to me, is Dependency Injection. It seems like the resources are being kept longer than I anticipated, the resources are being kept like in a static class and that rang me some alert for the long-term, the app allocated memory could be shortened. Other than that, I don't have any trouble with Navigation and Controller (for state management) so far. So while I had already applied GetX, I would say always be cautious with them. The author is also famous for his exaggerated claims and they got banned on Flutter.dev before, in case you did not know 🔍

**Comment by doannimble** [comment]
@sleepylee You're right, many people were blaming the DI issue in GetX and the author made the bad behaviors against. Anyway, I like the way it handles Navigation and Controller, and it may suitable for small project, which does not need too much DI.

**Comment by manh-t** [comment]
> should we then? 🐤 remember that we don't necessarily use everything from them; i.e if you prefer using a different package for DI / State Management / Navigation that's totally fine 😛 if we go with `GetX` we shall reduce many other parts too. The concern mainly to me is: do we need to put them on implemented? Can they be plugged in when init the project i.e: using `GetX` or `Fluro` as the choice of navigation 🤷

@sleepylee personally I agree to have `GetX` or `Fluro` as the choice of navigation when init the project. They are doing good their job, right? 😄 
I can imagine a case that needs our `Navigator`: When we are communicating with the native, then the native part requests to navigate to a screen. So we need to inject `navigator` to fulfill that request. I learn that from Growth 😺

**Comment by manh-t** [comment]
Closed since we implemented go_router in #96
