### ISSUE TITLE
Add the config for auto renaming the `json_serializable` variable as a snake case when building the generated files

### ISSUE THREAD

**Issue by manh-t** [nimblehq/flutter_templates#43]
## Why

When creating a `JsonSerializable` class, we usually add `@JsonKey` annotation before each variable to match with the field in API. Example:
```dart
@JsonSerializable()
class UserResponse {
  @JsonKey(name: 'user_name')
  final String userName;

  const UserResponse({
    required this.userName,
  });

  factory UserResponse.fromJson(Map<String, dynamic> json) {
    return _$UserResponseFromJson(json);
  }
}
```
By updating the `field_rename` [config](https://pub.dev/packages/json_serializable#build-configuration), we no longer take time to add `@JsonKey(name: 'snake_case')` before each variable. Then, the above example could be re-written like this:
```dart
@JsonSerializable()
class UserResponse {
  final String userName;

  const UserResponse({
    required this.userName,
  });

  factory UserResponse.fromJson(Map<String, dynamic> json) {
    return _$UserResponseFromJson(json);
  }
}
```
Please refer to [varun-matchmaking-flutter/build.yaml](https://gitlab.com/cloud_arv/agritech/service-matching/varun-matchmaking-flutter/-/blob/develop/build.yaml) for more details. (limited access)

**Updated**:
After implementing this feature, we should add a flag to init script to define which convention for API field we use. Default is `snake_case`.

The task list:

- [x] Add the config to the project.
- [ ] Update init script and update README

 
## Who Benefits?

Developers.

**Comment by sleepylee** [comment]
so should we make this a feature flag for the init script (default to this snake_case)? 🤔  @manh-t.

If there is a junior developer not knowing where to config this, he might be confused when there is an API that returns `camelCase` but the Json Response model doesn't parse correctly without the annotation 💡

**Comment by manh-t** [comment]
good idea @sleepylee , we should be able to update this config via init script, and add it to README ✍️ so the junior developer can read too 🙆‍♂️

**Comment by sleepylee** [comment]
@manh-t I added this 
![image](https://user-images.githubusercontent.com/13435717/157583031-7a39ef98-d8d0-47fc-91f8-c7b697c51b7f.png)

So later, for `example/` you can also annotate the same so the maintainers can understand the process easier 💪

**Comment by markgravity** [comment]
> good idea @sleepylee , we should be able to update this config via init script, and add it to README ✍️ so the junior developer can read too 🙆‍♂️

@manh-t  So we will add this idea in this issue or another? 🤔

**Comment by manh-t** [comment]
@markgravity I think we can add this idea to this issue for easy tracking. What do you think? 🙏

**Comment by markgravity** [comment]
> @markgravity I think we can add this idea to this issue for easy tracking. What do you think? 🙏

I agree 💪

**Comment by manh-t** [comment]
@markgravity I have updated the task list in the description. After implementing a task, you can check it 🙇
