### ISSUE TITLE
Fix: Bundle identifier does not allow underscore in iOS

### ISSUE THREAD

**Issue by manh-t** [nimblehq/flutter_templates#49]
## Issue

When initializing the project via script with the `PACKAGE_NAME` containing the underscore symbol `_` (example: `co.nimblehq.example.nimblehq_github`), we are not able to create the development provisioning profile (to run app on the real iOS device). It is because the bundle identifier is invalid according to [CFBundleIdentifier](https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundleidentifier): **The bundle ID string must contain only alphanumeric characters (A–Z, a–z, and 0–9), hyphens (-), and periods (.)**

**NOTE**: Android accepts the underscore symbol.
 
## Expected

When initializing the project via init script, if there is any underscore symbol, let's update it to _the hyphen (-)_ **for iOS only**
 
## Steps to reproduce

1. Init the project via script with `PACKAGE_NAME=co.nimblehq.example.nimblehq_github`
2. Open the `ios` project via Xcode
3. Target Runner > Signing & Capabilities.
4. Try to create the signing certificate with that bundle identifier.

**Comment by luongvo** [comment]
There is 1 more issue as I remember when working my IC, App Store does not accept app id has more than 4 parts lol e.g., `com.abc.app.android.debug` ❌
