### ISSUE TITLE
As a user, I can load the image, video, font assets

### ISSUE THREAD

**Issue by sleepylee** [nimblehq/flutter_templates#5]
## Why
We will need to configure yaml and a directory (`gen`) to keep all of our asset files, this is a repetitive step whenever setting up the application, so we should target to make it a part of the template.
 
## Who Benefits?
Every developer who uses this template.

**Comment by luongvo** [comment]
@doannimble please try to sync your working tasks in the correct status 🙏

**Comment by doannimble** [comment]
@luongvo Thank for reminding me 🙏
